### ISSUE TITLE
Página não carrega no Firefox

### ISSUE THREAD

**Issue by iomartin** [hsribei/rideboard#17]
Depois de fazer o login, fica eternamente em Loading...

Testado no FF 35.0 para Linux.

Consegui acessar normalmente no Chromium 39.0.2171.99.

**Comment by iomartin** [comment]
Correção: dado um número suficiente de refreshes na página e esperando alguns segundos, eventualmente consigo acessar pelo FF.

Notei que isto também ocorre no Chromium, embora neste tem sido necessário menor número de tentativas até conseguir carregar a página.

**Comment by obvio171** [comment]
É, este problema intermitente está enchendo o saco de todo mundo, e ainda não consegui descobrir exatamente o que está acontecendo (é um [heisenbug](http://en.wikipedia.org/wiki/Heisenbug) :/).

Parece que é uma zica entre o código de estabelecimento de conexão do MeteorJS e os browsers (havia reports que tinha um bug no Chromium; provavelmente um equivalente no Firefox também). 

Ainda estou investigando junto com os desenvolvedores do Meteor aqui: https://github.com/meteor/meteor/issues/3509

Uma outra gambiarra que tem funcionado para mim é, quando trava no Loading, clicar na aba "Perfil" e depois clicar de volta em "Início" depois (às vezes repetindo isso algumas vezes). Como são conjuntos de dados diferentes que o site tem que pedir do servidor, às vezes ele dá uma "resetada" no estado pendente e volta a funcionar.

Para receber caronas, também tem o fallback de assinar por email, mas o gargalo mesmo é ter mais gente postando caronas. Vou correr pra resolver isso logo.

**Comment by iomartin** [comment]
Gentle bump.

Alguma novidade? As aulas começam logo mais, e para muitos será o primeiro contato com o site. Seria bacana que tivessem uma boa experiência, o que ajudaria bastante a alavancar o número de usuários.

**Comment by daviuezono** [comment]
Pra mim carrega normal.
Como o Helder disse no post um pouco acima, em horários de pico ele fica lento mesmo, e a tela em branca (Loading...) é tipo um time-out.
A gambiarra de clicar no perfil e voltar para Início funciona as vezes, mas nem sempre.

**Comment by hilder-vitor** [comment]
Estou tentando acessar usando o Firefox 35.0.1 instalado em um Ubuntu 14.04.

No console de javascript do meu Firefox, está aparecendo a seguinte mensagem:

"A conexão com wss://ddp--6429--5490d4eec0c60511550004d2.meteor.com/sockjs/195/c77km_5y/websocket foi interrompida durante o carregamento da página."

Além disso, ele diz que o erro vem da linha 32 do arquivo
http://www.muraldecaronas.org/236fe169194d7015a8771022d13382d1ed30156d.js
