### ISSUE TITLE
Permitir que usuário atualize data e horário da carona

### ISSUE THREAD

**Issue by iomartin** [hsribei/rideboard#18]
Atualmente isto não é possível. Apenas número de assentos, preço e detalhes podem ser alterados.

**Comment by obvio171** [comment]
Nossa, verdade. Passou desapercebido isso. Obrigado por reportar! Conserto hoje mesmo.

**Comment by iomartin** [comment]
Oi Helder, você conseguiu arrumar isso? Obrigado.

**Comment by hsribei** [comment]
Opa, foi mal, achei que era algo mais trivial. Ainda estou investigando aqui: https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/11

**Comment by iomartin** [comment]
bump
